# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpslpajJqCNxRwpm-hqW9Y6KrRNkI2kv
"""

import numpy as np
import matplotlib.pyplot as plt
# Time range (seconds)
t = np.linspace(0, 5000, 200)
R = 100e-9
# Typical order of magnitude for drug diffusion in polymers
D_normal = 1e-18
D_triggered = 5e-18
# increased diffusion due to ultrasound
# Rate constants (k ∝ D/R^2)
k_normal = D_normal / (R**2)
k_triggered = D_triggered / (R**2)
def drug_release(k, t):
    return 1 - np.exp(-k * t)
release_normal = drug_release(k_normal, t) * 100
release_triggered = drug_release(k_triggered, t) * 100
plt.figure()
plt.plot(t, release_normal, label="Normal Diffusion")
plt.plot(t, release_triggered, linestyle='--', label="Triggered Release (Ultrasound)")
plt.xlabel("Time (s)")
plt.ylabel("Drug Released (%)")
plt.title("Diffusion-Controlled Drug Release from Nanoparticle")
plt.legend()
plt.grid()
plt.savefig("results.png")
plt.show()

